cc_library(
    name = "list_swap",
    srcs = ["list_swap.C"],
)

cc_library(
    name = "member_swap",
    srcs = ["member_swap.C"],
)

cc_library(
    name = "nonmember_swap_friend_forward",
    srcs = ["nonmember_swap_friend_forward.C"],
)

cc_library(
    name = "nonmember_swap_friend",
    srcs = ["nonmember_swap_friend.C"],
)

cc_library(
    name = "nonmember_swap_func",
    srcs = ["nonmember_swap_func.C"],
)

cc_library(
    name = "nonmember_swap_none",
    srcs = ["nonmember_swap_none.C"],
)

cc_library(
    name = "nonmember_swap_std_only",
    srcs = ["nonmember_swap_std_only.C"],
)

cc_library(
    name = "nonmember_swap_std",
    srcs = ["nonmember_swap_std.C"],
)

cc_library(
    name = "std_swap_copyable",
    srcs = ["std_swap_copyable.C"],
)

cc_library(
    name = "std_swap_movable",
    srcs = ["std_swap_movable.C"],
)

cc_library(
    name = "std_swap_nonmovable",
    srcs = ["std_swap_nonmovable.C"],
)

cc_library(
    name = "std_swap_noncopyable",
    srcs = ["std_swap_noncopyable.C"],
)

cc_library(
    name = "swap_rollback",
    srcs = ["swap_rollback.C"],
)

cc_library(
    name = "vector_empty",
    srcs = ["vector_empty.C"],
)

cc_library(
    name = "vector_swap",
    srcs = ["vector_swap.C"],
)
